####tamil=input("Enter the the tamil mark:")
####english=input("Enter the the english mark:")
####maths=input("Enter the the maths mark:")
####social=input("Enter the the social mark:")
####science=input("Enter the the science mark:")
####Tamil=input("Enter the the subject:")
####English=input("Enter the the subject:")
####Maths=input("Enter the the subject:")
####Social=input("Enter the the subject:")
####Science=input("Enter the the subject:")
####total=(int(tamil)+int(english)+int(maths)+int(social)+int(science))
####print("╔════════════════════╦══════════╗")
####print(f"║ {Tamil}             ║   {tamil}    ║")
####print("║════════════════════╬══════════║")
####print(f"║ {English}           ║   {english}    ║")
####print("║════════════════════╬══════════║")
####print(f"║ {Maths}             ║   {maths}    ║")
####print("║════════════════════╬══════════║")
####print(f"║ {Social}            ║   {social}    ║")
####print("║════════════════════╬══════════║")
####print(f"║ {Science}           ║   {science}    ║")
####print("║════════════════════╬══════════║")
####print(f"║ Total               ║   {total}    ║")
####print("╚════════════════════╩══════════╝")
####



tamil=input("Enter the the tamil mark:")
english=input("Enter the the english mark:")
maths=input("Enter the the maths mark:")
social=input("Enter the the social mark:")
science=input("Enter the the science mark:")
Tamil=input("Enter the the subject:")
English=input("Enter the the subject:")
Maths=input("Enter the the subject:")
Social=input("Enter the the subject:")
Science=input("Enter the the subject:")
total=(int(tamil)+int(english)+int(maths)+int(social)+int(science))
Total=("TOTAL")
TAMIL=str(tamil)
ENGLISH=str(english)
MATHS=str(maths)
SOCIAL=str(social)
SCIENCE=str(science)
TOTAL=str(total)

print("╔═════════════════════╦════════════╗")
print(f"║ {Tamil}{' '*(20-len(Tamil))}║  {tamil}{' '*(10-len(TAMIL))}║")
print("║═════════════════════╬════════════║")
print(f"║ {English}{' '*(20-len(English))}║  {english}{' '*(10-len(ENGLISH))}║")
print("║═════════════════════╬════════════║")
print(f"║ {Maths}{' '*(20-len(Maths))}║  {maths}{' '*(10-len(MATHS))}║")
print("║═════════════════════╬════════════║")
print(f"║ {Social}{' '*(20-len(Social))}║  {social}{' '*(10-len(SOCIAL))}║")
print("║═════════════════════╬════════════║")
print(f"║ {Science}{' '*(20-len(Science))}║  {science}{' '*(10-len(SCIENCE))}║")
print("║═════════════════════╬════════════║")
print(f"║ {Total}{' '*(20-len(Total))}║  {total}{' '*(10-len(TOTAL))}║")
print("╚═════════════════════╩════════════╝")



